/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package arbolgrafico;

import java.awt.*;
import javax.swing.*;


public class Gui extends javax.swing.JFrame  {

    private TreeSet simulador;
    private int bandera;
    public Gui() {
        bandera=0;
        simulador = new TreeSet();
        initComponents();
        this.jInternalFrame2.setVisible(true);
        this.lblCnodos.setVisible(false);
        this.lblChojas.setVisible(false);
        this.altura.setVisible(false);
        this.nodos.setVisible(false);
        this.inicializar(false);
    }

    private void inicializar(boolean enable) {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jPanel4 = new javax.swing.JPanel();
        nodos = new javax.swing.JLabel();
        lblCnodos = new javax.swing.JTextField();
        altura = new javax.swing.JLabel();
        lblChojas = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        iniciar = new javax.swing.JButton();
        botonGuardar = new javax.swing.JButton();
        botonAbrir = new javax.swing.JButton();
        btnfull = new javax.swing.JButton();
        btnperfect = new javax.swing.JButton();
        btndegenerate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setOpaque(false);

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 255, 0)));
        jDesktopPane1.setOpaque(false);

        jInternalFrame2.setBackground(new java.awt.Color(255, 255, 255));
        jInternalFrame2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jInternalFrame2.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        jInternalFrame2.setForeground(new java.awt.Color(255, 255, 255));
        jInternalFrame2.setEnabled(false);
        jInternalFrame2.setFocusCycleRoot(false);
        jInternalFrame2.setFont(new java.awt.Font("Prestige Elite Std", 0, 11)); // NOI18N
        jInternalFrame2.setVisible(true);

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1258, Short.MAX_VALUE)
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );

        jDesktopPane1.add(jInternalFrame2);
        jInternalFrame2.setBounds(0, 0, 1260, 440);

        jPanel4.setOpaque(false);

        nodos.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        nodos.setForeground(new java.awt.Color(0, 51, 153));
        nodos.setText("Numero de hojas");

        lblCnodos.setEditable(false);
        lblCnodos.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lblCnodos.setForeground(new java.awt.Color(0, 51, 204));

        altura.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        altura.setForeground(new java.awt.Color(0, 51, 153));
        altura.setText("Altura");

        lblChojas.setEditable(false);
        lblChojas.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lblChojas.setForeground(new java.awt.Color(0, 51, 204));

        btnLimpiar.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setName("btnLimpiar"); // NOI18N
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(nodos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCnodos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(altura)
                .addGap(18, 18, 18)
                .addComponent(lblChojas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimpiar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nodos)
                    .addComponent(lblCnodos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(altura)
                    .addComponent(lblChojas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        iniciar.setBackground(new java.awt.Color(255, 255, 255));
        iniciar.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        iniciar.setText("Empezar");
        iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarActionPerformed(evt);
            }
        });

        botonGuardar.setBackground(new java.awt.Color(255, 255, 255));
        botonGuardar.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        botonGuardar.setText("Guardar");
        botonGuardar.setName("botonGuardar"); // NOI18N
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        botonAbrir.setBackground(new java.awt.Color(255, 255, 255));
        botonAbrir.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        botonAbrir.setText("Abrir");
        botonAbrir.setName("botonGuardar"); // NOI18N
        botonAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAbrirActionPerformed(evt);
            }
        });

        btnfull.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btnfull.setText("¿Esta lleno?");
        btnfull.setToolTipText("");
        btnfull.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfullActionPerformed(evt);
            }
        });

        btnperfect.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btnperfect.setText("¿Es perfecto?");
        btnperfect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnperfectActionPerformed(evt);
            }
        });

        btndegenerate.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btndegenerate.setText("¿Es degenerado?");
        btndegenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndegenerateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(552, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(iniciar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonAbrir))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnfull)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnperfect)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btndegenerate)))
                .addGap(518, 518, 518))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iniciar)
                    .addComponent(botonGuardar)
                    .addComponent(botonAbrir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnfull)
                    .addComponent(btnperfect)
                    .addComponent(btndegenerate))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(545, 545, 545)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 1023, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 40, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndegenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndegenerateActionPerformed
        // TODO add your handling code here:
        if(simulador.degenerado()){
            JOptionPane.showMessageDialog(null, "El arbol es degenerado");
        }else JOptionPane.showMessageDialog(null, "El arbol no es degenerado");
    }//GEN-LAST:event_btndegenerateActionPerformed

    private void btnperfectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnperfectActionPerformed
        // TODO add your handling code here:
        if(simulador.perfecto()){
            JOptionPane.showMessageDialog(null, "Es perfecto");
        }else JOptionPane.showMessageDialog(null, "No es perfecto");
    }//GEN-LAST:event_btnperfectActionPerformed

    private void btnfullActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfullActionPerformed
        // TODO add your handling code here:
        if(simulador.isFull()){
            JOptionPane.showMessageDialog(null, "El arbol esta lleno");
        }else JOptionPane.showMessageDialog(null, "El arbol no esta lleno");
    }//GEN-LAST:event_btnfullActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        this.simulador.limpiar();
        complementos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void botonAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAbrirActionPerformed
        // TODO add your handling code here:
        this.simulador.abrir();
        /*if(bandera==0){
            this.jInternalFrame2.setVisible(false);
            this.lblCnodos.setVisible(false);
            this.lblChojas.setVisible(false);
        }else*/  complementos();
    }//GEN-LAST:event_botonAbrirActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        this.simulador.Guardar();
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarActionPerformed
        complementos();
        jInternalFrame2.setEnabled(false);
        try {
            boolean otroJuego = true;
            this.lblChojas.setText("0");
            do{
                this.simulador.iniciar();
                //JOptionPane.showMessageDialog(null, "El dato fue insertado correctamente", " ...", 1);
                if(bandera==0){

                    this.jInternalFrame2.setVisible(true);
                    this.lblCnodos.setVisible(true);
                    this.lblChojas.setVisible(true);

                }else  complementos();

                int resp = JOptionPane.showConfirmDialog(null, "¿Esta seguro?", "Alerta!", JOptionPane.YES_NO_OPTION);
                System. out. println("hola "+resp);
                String r="";
                if (resp==0){
                    r="si";
                }else
                r="no";
                if(r.equalsIgnoreCase("si")){
                    complementos();
                    bandera=1;

                }else
                otroJuego=this.simulador.respuesta(r);
            }while(otroJuego);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se pudo insertar el dato", "Intenta de nuevo...", 0);

        }
        jInternalFrame2.setEnabled(true);
    }//GEN-LAST:event_iniciarActionPerformed

    public void complementos(){
        this.repintarArbol();
        this.lblCnodos.setText("");
        this.lblCnodos.setText(this.simulador.CantidadHojas());
        this.lblChojas.setText("");
        this.lblChojas.setText(String.valueOf(this.simulador.alturaArbol()));
        System.out.println(""+this.simulador.alturaArbol());
        this.lblCnodos.setVisible(true);
        this.lblChojas.setVisible(true);
        this.altura.setVisible(true);
        this.nodos.setVisible(true);

        
    }
    private void repintarArbol() {
       this.jDesktopPane1.removeAll();
        Rectangle tamaño = this.jInternalFrame2.getBounds();
        this.jInternalFrame2 = null;
        this.jInternalFrame2 = new JInternalFrame("Arbol", true);
        this.jDesktopPane1.add(this.jInternalFrame2, JLayeredPane.DEFAULT_LAYER);
        this.jInternalFrame2.setVisible(true);
        this.jInternalFrame2.setBounds(tamaño);
        this.jInternalFrame2.setEnabled(true);
        this.jInternalFrame2.add(this.simulador.getDibujo(), BorderLayout.CENTER);
    }


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel altura;
    private javax.swing.JButton botonAbrir;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btndegenerate;
    private javax.swing.JButton btnfull;
    private javax.swing.JButton btnperfect;
    private javax.swing.JButton iniciar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField lblChojas;
    private javax.swing.JTextField lblCnodos;
    private javax.swing.JLabel nodos;
    // End of variables declaration//GEN-END:variables
}
